//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JooleDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduct()
        {
            this.tblTypes = new HashSet<tblType>();
            this.tblTypes1 = new HashSet<tblType>();
            this.tblTypes2 = new HashSet<tblType>();
            this.tblTypes3 = new HashSet<tblType>();
            this.tblTypes4 = new HashSet<tblType>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string Series { get; set; }
        public int ModelYear { get; set; }
        public int DepartmentID { get; set; }
        public int SubCategoryID { get; set; }
        public int SalesPersonID { get; set; }
        public string ProductImagePath { get; set; }
    
        public virtual tblSubCategory tblSubCategory { get; set; }
        public virtual tblSubCategory tblSubCategory1 { get; set; }
        public virtual tblSubCategory tblSubCategory2 { get; set; }
        public virtual tblSubCategory tblSubCategory3 { get; set; }
        public virtual tblSubCategory tblSubCategory4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblType> tblTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblType> tblTypes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblType> tblTypes2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblType> tblTypes3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblType> tblTypes4 { get; set; }
    }
}
