//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JooleDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblType()
        {
            this.tblTypeOptValues = new HashSet<tblTypeOptValue>();
            this.tblTypeOptValues1 = new HashSet<tblTypeOptValue>();
            this.tblTypeOptValues2 = new HashSet<tblTypeOptValue>();
            this.tblTypeOptValues3 = new HashSet<tblTypeOptValue>();
            this.tblTypeOptValues4 = new HashSet<tblTypeOptValue>();
            this.tblTypeSpecValues = new HashSet<tblTypeSpecValue>();
            this.tblTypeSpecValues1 = new HashSet<tblTypeSpecValue>();
            this.tblTypeSpecValues2 = new HashSet<tblTypeSpecValue>();
            this.tblTypeSpecValues3 = new HashSet<tblTypeSpecValue>();
            this.tblTypeSpecValues4 = new HashSet<tblTypeSpecValue>();
        }
    
        public int TypeID { get; set; }
        public string TypeName { get; set; }
        public bool IsTOption { get; set; }
        public int ProductID { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblProduct tblProduct1 { get; set; }
        public virtual tblProduct tblProduct2 { get; set; }
        public virtual tblProduct tblProduct3 { get; set; }
        public virtual tblProduct tblProduct4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTypeOptValue> tblTypeOptValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTypeOptValue> tblTypeOptValues1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTypeOptValue> tblTypeOptValues2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTypeOptValue> tblTypeOptValues3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTypeOptValue> tblTypeOptValues4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTypeSpecValue> tblTypeSpecValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTypeSpecValue> tblTypeSpecValues1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTypeSpecValue> tblTypeSpecValues2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTypeSpecValue> tblTypeSpecValues3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTypeSpecValue> tblTypeSpecValues4 { get; set; }
    }
}
