//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JooleDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTypeOptValue
    {
        public int TypeOptID { get; set; }
        public string Opt { get; set; }
        public int TypeID { get; set; }
    
        public virtual tblType tblType { get; set; }
        public virtual tblType tblType1 { get; set; }
        public virtual tblType tblType2 { get; set; }
        public virtual tblType tblType3 { get; set; }
        public virtual tblType tblType4 { get; set; }
    }
}
